import type { Product } from '@/types';

const products: Product[] = [
  {
    id: '1',
    name: 'AI Content Suite Pro',
    description: 'A comprehensive suite of AI-powered tools for content creation, editing, and optimization. Boost your productivity and creativity.',
    price: 49.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'AI robot',
    category: 'Digital Services',
  },
  {
    id: '2',
    name: 'CloudFlow Manager',
    description: 'Manage your projects seamlessly with this intuitive cloud-based project management tool. Ideal for teams of all sizes.',
    price: 29.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'cloud project',
    category: 'Software',
  },
  {
    id: '3',
    name: 'FitGenius AI Planner',
    description: 'Get personalized fitness plans generated by AI. Tailored to your goals, preferences, and fitness level.',
    price: 19.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'fitness app',
    category: 'Digital Services',
  },
  {
    id: '4',
    name: 'DataGuardian Backup',
    description: 'Secure and reliable data backup service for peace of mind. Protect your valuable digital assets effortlessly.',
    price: 9.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'data security',
    category: 'Software',
  },
  {
    id: '5',
    name: 'LingoLeap Interactive Course',
    description: 'Learn new languages with our interactive online courses. Engaging lessons and real-time feedback.',
    price: 79.00,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'online course',
    category: 'Digital Services',
  },
  {
    id: '6',
    name: 'E-Book: Mastering Next.js',
    description: 'A comprehensive guide to mastering Next.js, from fundamentals to advanced techniques. Perfect for developers.',
    price: 24.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'ebook cover',
    category: 'E-books',
  }
];

export const getProducts = (): Product[] => {
  return products;
};

export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
};

export const getProductsByCategory = (category: string): Product[] => {
  if (category === 'All') return products;
  return products.filter(product => product.category === category);
}

export const getCategories = (): string[] => {
  const categories = new Set(products.map(p => p.category));
  return ['All', ...Array.from(categories)];
}
