// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtdlaemduhyorzuzzphs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZGxhZW1kdWh5b3J6dXp6cGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODE5MTcsImV4cCI6MjA2NTQ1NzkxN30.Y_sZtvwpdUY-XLcofJAw199H7YN6b6GIGe7MKgtbEXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);